Repository CSID-DGU/2024-2-OSSProj-Osori-FE-01, pull requests merged in 2024-10, with the labels that each got.

#7 [Feat] 메인페이지 이미지 수정 및 브랜치 테스트
  src/views/feed/AkoStampWriteView.vue
  src/views/mainpage/MainpageView.vue
Labels: ✨ feature

#10 [Rename] [Feat] Header, Footer 파일 이동 및 Fonts 폴더에 Fonts.css 추가
  src/assets/fonts/fonts.css
  src/components/layout/FeedLayout.vue
  src/components/layout/Footer.vue
  src/components/layout/Header.vue
  src/main.js
  src/views/calendar/CalendarMainView.vue
  src/views/feed/AkoStampWriteView.vue
  src/views/login/mypage/MypageView.vue
  src/views/mainpage/MainpageScript.js
  src/views/mainpage/MainpageView.vue
  tailwind.config.js
Labels: ✨ feature, 지원

#11 [Feature] #6 - Ako Stamp Write 구현 및 폰트 추가
  public/font/NanumSquareRoundB.ttf
  public/font/NanumSquareRoundL.ttf
  public/font/NanumSquareRoundR.ttf
  src/assets/images/back.svg
  src/assets/styles/global.css
  src/router/index.js
  src/views/feed/AkoStampBoard.vue
  src/views/feed/AkoStampFollow.vue
  src/views/feed/AkoStampWriteView.vue
Labels: ✨ feature, 민

#12 [Feat] Footer 라우터 절대 경로로 수정 및 메인페이지 캘린더 페이지 개발
  src/components/layout/Footer.vue
  src/main.js
  src/views/calendar/CalendarMainView.vue
  src/views/mainpage/MainpageView.vue
Labels: ✨ feature

#13 [Design} Footer.vue 디자인 수정
  src/components/layout/Footer.vue
  src/views/calendar/CalendarMainView.vue
Labels: 지원

#14 [Design] 메인페이지 기능 추가 및 디자인 수정, 캘린더, 마이페이지 디자인 수정, 404페이지 수정 등
  package-lock.json
  package.json
  src/App.vue
  src/assets/Icons/FooterIcons/CalendarIcon.vue
  src/assets/Icons/FooterIcons/HomeIcon.vue
  src/assets/Icons/FooterIcons/ListIcon.vue
  src/assets/Icons/FooterIcons/RefreshIcon.vue
  src/assets/Icons/FooterIcons/UserIcon.vue
  src/assets/Icons/akoming/arrow-right.svg
  src/assets/Icons/akoming/stamp/color/colork.svg
  src/assets/Icons/akoming/stamp/color/colorm.svg
  src/assets/Icons/akoming/stamp/gray/grayk.svg
  src/assets/Icons/akoming/stamp/gray/graym.svg
  src/assets/Icons/akoming/todo/akofolio.svg
  src/assets/Icons/akoming/todo/akojaguk.svg
  src/assets/Icons/akoming/todo/attendance.svg
  src/assets/Icons/akoming/todo/comment.svg
  src/assets/fonts/fonts.css
  src/components/layout/BottomNavigationBar.vue
  src/components/layout/Footer.vue
  src/components/layout/Header.vue
  src/views/calendar/CalendarMainScript.js
  src/views/calendar/CalendarMainView.vue
  src/views/feed/AkoStampWriteView.vue
  src/views/login/login/LoginView.vue
  src/views/login/mypage/MypageScript.js
  src/views/login/mypage/MypageView.vue
  src/views/login/signup/SignupView.vue
  src/views/mainpage/MainpageView.vue
  src/views/test/NotFound.vue
  src/views/test/NotFound2.vue
  src/views/test/SignUpForm2.vue
  tailwind.config.js
Labels: enhancement, ✨ feature

#15 [Feature] 캘린더, 마이페이지 수정, 로고 로딩 페이지 구현
  src/assets/Icons/akoming/Akoming-logo.svg
  src/components/LogoLoading.vue
  src/views/calendar/CalendarMainView.vue
  src/views/login/login/LoginView.vue
  src/views/login/mypage/MypageView.vue
  src/views/login/signup/SignupView.vue
Labels: ✨ feature

#17 [Feature] #16 - 메인 피드 페이지 구현 및 404페이지 이동
  src/components/common/feed/CommentInput.vue
  src/components/common/feed/CommentList.vue
  src/components/common/feed/FollowStats.vue
  src/components/common/feed/FriendGoal.vue
  src/components/common/feed/MyGoal.vue
  src/components/common/feed/SearchBar.vue
  src/router/index.js
  src/views/NotFound.vue
  src/views/feed/FeedPageStyle.css
  src/views/feed/MainFeedPage.vue
Labels: ✨ feature

#19 [Feature] 캘린더 임시 데이터 추가 및 피드페이지 간격 수정
  src/views/calendar/CalendarMainScript.js
  src/views/feed/MainFeedPage.vue
Labels: ✨ feature

#20 [Docs] 회의록 링크 수정 및 로그인 회원가입 배경색 오류 수정
  docs/회의록.md
  src/views/login/login/LoginView.vue
  src/views/login/signup/SignupView.vue
Labels: 🐛 bug, documentation

#24 [Feature] #6 - 아코스탬프 팔로워, 팔로잉 목록 구현
  src/views/feed/AkoStampFollow.vue
Labels: ✨ feature, 민

#25 [Feature] 캘린더 페이지 및 마이페이지 백엔드 로직 작성
  package-lock.json
  package.json
  src/assets/Icons/akoming/arrowright.svg
  src/views/calendar/CalendarMainScript.js
  src/views/calendar/CalendarMainView.vue
  src/views/login/mypage/MypageScript.js
  src/views/login/mypage/MypageView.vue
  webpack.config.js
Labels: ✨ feature

#27 [Feature] 아코폴리오 페이지 구현 중
  package-lock.json
  package.json
  src/assets/images/AddFile.svg
  src/main.js
  src/router/index.js
  src/store/index.js
  src/views/akopolio/SelectCalendar.vue
  src/views/akopolio/akopolioCreate.vue
  src/views/akopolio/akopolioMain.vue
  src/views/akopolio/paginationNav.vue
Labels: ✨ feature, 예빈

#28 [Fix] #26 - Footer.vue 에서 아코폴리오 페이지 연결되도록 수정
  src/components/layout/Footer.vue
  src/components/layout/PortfolioLayout.vue
  src/router/index.js
  src/views/akopolio/akopolioMain.vue
  src/views/login/mypage/MypageView.vue
Labels: 지원

#29 [Feature] #26 아코폴리오 작성 시 목록 연동
  src/store/index.js
  src/views/akopolio/akopolioCreate.vue
  src/views/akopolio/akopolioMain.vue
  src/views/akopolio/paginationNav.vue
Labels: ✨ feature, 예빈

#30 [Feature] #26 아코폴리오 상세보기 페이지 구현
  src/router/index.js
  src/store/index.js
  src/views/akopolio/akopolioCreate.vue
  src/views/akopolio/akopolioDetail.vue
  src/views/akopolio/akopolioMain.vue
Labels: ✨ feature, 예빈

#31 [Docs] 12차 회의록 작성 및 메인 페이지 백엔드 연결 로직 작성 중
  docs/회의록.md
  src/views/login/mypage/MypageView.vue
  src/views/mainpage/MainpageScript.js
Labels: documentation, ✨ feature, 지원

#33 [Feature] #26 아코폴리오 수정 페이지 구현
  src/router/index.js
  src/store/index.js
  src/views/akopolio/akopolioEdit.vue
Labels: ✨ feature, 예빈
