Repository CSID-DGU/2024-2-OSSProj-Osori-FE-01, pull requests merged in 2024-11, with the labels that each got.

#34 Feat: 아코 캐릭터 svg 업로드
  src/assets/Icons/akoming/mainpage/ako-02.svg
  src/assets/Icons/akoming/mainpage/ako-03.svg
  src/assets/Icons/akoming/mainpage/ako-04.svg
  src/assets/Icons/akoming/mainpage/ako-05.svg
  src/assets/Icons/akoming/mainpage/ako-06.svg
Labels: 지원

#35 [Feature] #26 -아코폴리오Edit 태그 기능 수정
  src/views/akopolio/akopolioEdit.vue
Labels: ✨ feature, 예빈

#38 [Feat] Tailwind CSS purge 설정 추가 및 메인페이지 백엔드 로직 작성
  .env
  src/views/mainpage/MainpageView.vue
  tailwind.config.js
  vue.config.js
Labels: ✨ feature, 지원

#39 [Fix] Tailwind CSS 버전 오류 수정
  tailwind.config.js
Labels: 🐛 bug, 지원

#40 Fix: proxy 설정 수정
  .env
  public/favicon.ico
  public/index.html
  vue.config.js
Labels: 지원

#42 Fix: 백엔드 변경에 맞추어 회원가입 vue및 js 수정
  src/views/login/signup/SignupScript.js
  src/views/login/signup/SignupView.vue
Labels: 지원, 🌠Changes

#43 [Fix] 회원가입 페이지 실명 관련 로직 삭제
  src/views/login/signup/SignupScript.js
  src/views/login/signup/SignupView.vue
Labels: ✨ feature

#44 [Fix] 로그인 회원가입 백엔드 연동 구현
  src/views/login/login/LoginScript.js
  src/views/login/login/LoginView.vue
  src/views/login/signup/SignupScript.js
Labels: ✨ feature, 지원

#46 [Feat] - 마이페이지 더보기 로직 작성 및 composition api로 수정
  src/views/login/login/LoginScript.js
  src/views/login/mypage/MypageScript.js
  src/views/login/mypage/MypageView.vue
  vue.config.js
Labels: enhancement

#49 [Feature] #26 - 아코폴리오 백엔드 연동 전
  docs/회의록.md
  src/router/index.js
  src/views/akopolio/akopolioCreate.vue
  src/views/akopolio/akopolioDetail.vue
  src/views/akopolio/akopolioEdit.vue
  src/views/akopolio/akopolioMain.vue
Labels: 예빈

#56 [Feat] #26 - 백엔드 로직 및 이미지 컨테이너 생성
  src/views/akopolio/Edit/akopolioEdit.vue
  src/views/akopolio/Edit/edit.js
  src/views/akopolio/create/akopolioCreate.vue
  src/views/akopolio/create/create.js
  src/views/akopolio/detail/akopolioDetail.vue
  src/views/akopolio/detail/detail.js
Labels: ✨ feature

#62 [Feature] #26 - 이미지 업로드 수정
  src/views/akopolio/Edit/edit.js
  src/views/akopolio/create/create.js
Labels: ✨ feature
